# Generated by Django 5.0.1 on 2024-02-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(to='main.product'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
