# Generated by Django 5.0.1 on 2024-03-05 20:37

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=main.utils.create_new_id, editable=False, max_length=10, unique=True),
        ),
    ]
